
# CUDA definitions for all CasADi atomic operations
#   Nearly all symbolic, scalar operations are included here.
#   Exhaustive list: https://github.com/casadi/casadi/blob/main/casadi/core/calculus.hpp

# CUDA libraries may need to be manually added for compilation:
#   export PATH="/usr/local/cuda-12.3/bin:$PATH"
#   export LD_LIBRARY_PATH="/usr/local/cuda-12.3/lib64:$LD_LIBRARY_PATH"

from casadi import (
    OP_ASSIGN, OP_ADD, OP_SUB, OP_MUL, OP_DIV, OP_NEG, OP_EXP, OP_LOG, OP_POW,
    OP_CONSTPOW, OP_SQRT, OP_SQ, OP_TWICE, OP_SIN, OP_COS, OP_TAN, OP_ASIN,
    OP_ACOS, OP_ATAN, OP_LT, OP_LE, OP_EQ, OP_NE, OP_NOT, OP_AND, OP_OR,
    OP_FLOOR, OP_CEIL, OP_FMOD, OP_FABS, OP_SIGN, OP_COPYSIGN, OP_IF_ELSE_ZERO,
    OP_ERF, OP_FMIN, OP_FMAX, OP_INV, OP_SINH, OP_COSH, OP_TANH, OP_ASINH,
    OP_ACOSH, OP_ATANH, OP_ATAN2, OP_CONST, OP_INPUT, OP_OUTPUT
)

OP_CUDA_DICT = {
    OP_ASSIGN:              "\n        work[env_idx + %d] = work[env_idx + %d];",
    OP_ADD:                 "\n        work[env_idx + %d] = work[env_idx + %d] + work[env_idx + %d];",
    OP_SUB:                 "\n        work[env_idx + %d] = work[env_idx + %d] - work[env_idx + %d];",
    OP_MUL:                 "\n        work[env_idx + %d] = work[env_idx + %d] * work[env_idx + %d];",
    OP_DIV:                 "\n        work[env_idx + %d] = work[env_idx + %d] / work[env_idx + %d];",
    OP_NEG:                 "\n        work[env_idx + %d] = -work[env_idx + %d];",
    OP_EXP:                 "\n        work[env_idx + %d] = exp(work[env_idx + %d]);",
    OP_LOG:                 "\n        work[env_idx + %d] = log(work[env_idx + %d]);",
    OP_POW:                 "\n        work[env_idx + %d] = pow(work[env_idx + %d], work[env_idx + %d]);",
    OP_CONSTPOW:            "\n        work[env_idx + %d] = pow(work[env_idx + %d], work[env_idx + %d]);",
    OP_SQRT:                "\n        work[env_idx + %d] = sqrt(work[env_idx + %d]);",
    OP_SQ:                  "\n        work[env_idx + %d] = work[env_idx + %d] * work[env_idx + %d];",
    OP_TWICE:               "\n        work[env_idx + %d] = 2.*(work[env_idx + %d]);",
    OP_SIN:                 "\n        work[env_idx + %d] = sin(work[env_idx + %d]);",
    OP_COS:                 "\n        work[env_idx + %d] = cos(work[env_idx + %d]);",
    OP_TAN:                 "\n        work[env_idx + %d] = tan(work[env_idx + %d]);",
    OP_ASIN:                "\n        work[env_idx + %d] = asin(work[env_idx + %d]);",
    OP_ACOS:                "\n        work[env_idx + %d] = acos(work[env_idx + %d]);",
    OP_ATAN:                "\n        work[env_idx + %d] = atan(work[env_idx + %d]);",
    OP_LT:                  "\n        work[env_idx + %d] = work[env_idx + %d] < work[env_idx + %d];",
    OP_LE:                  "\n        work[env_idx + %d] = work[env_idx + %d] <= work[env_idx + %d];",
    OP_EQ:                  "\n        work[env_idx + %d] = work[env_idx + %d] == work[env_idx + %d];",
    OP_NE:                  "\n        work[env_idx + %d] = work[env_idx + %d] != work[env_idx + %d];",
    OP_NOT:                 "\n        work[env_idx + %d] = !work[env_idx + %d];",
    OP_AND:                 "\n        work[env_idx + %d] = work[env_idx + %d] && work[env_idx + %d];",
    OP_OR:                  "\n        work[env_idx + %d] = work[env_idx + %d] || work[env_idx + %d];",
    OP_FLOOR:               "\n        work[env_idx + %d] = floor(work[env_idx + %d]);",
    OP_CEIL:                "\n        work[env_idx + %d] = ceil(work[env_idx + %d]);",
    OP_FMOD:                "\n        work[env_idx + %d] = fmod(work[env_idx + %d], work[env_idx + %d]);",
    OP_FABS:                "\n        work[env_idx + %d] = fabs(work[env_idx + %d]);",
    OP_SIGN:                "\n        work[env_idx + %d] = sign(work[env_idx + %d]);",
    OP_COPYSIGN:            "\n        work[env_idx + %d] = copysign(work[env_idx + %d], work[env_idx + %d]);",
    OP_IF_ELSE_ZERO:        "\n        work[env_idx + %d] = (work[env_idx + %d] != 0) ? work[env_idx + %d] : 0;",
    OP_ERF:                 "\n        work[env_idx + %d] = erf(work[env_idx + %d]);",
    OP_FMIN:                "\n        work[env_idx + %d] = fmin(work[env_idx + %d], work[env_idx + %d]);",
    OP_FMAX:                "\n        work[env_idx + %d] = fmax(work[env_idx + %d], work[env_idx + %d]);",
    OP_INV:                 "\n        work[env_idx + %d] = 1./(work[env_idx + %d]);",
    OP_SINH:                "\n        work[env_idx + %d] = sinh(work[env_idx + %d]);",
    OP_COSH:                "\n        work[env_idx + %d] = cosh(work[env_idx + %d]);",
    OP_TANH:                "\n        work[env_idx + %d] = tanh(work[env_idx + %d]);",
    OP_ASINH:               "\n        work[env_idx + %d] = asinh(work[env_idx + %d]);",
    OP_ACOSH:               "\n        work[env_idx + %d] = acosh(work[env_idx + %d]);",
    OP_ATANH:               "\n        work[env_idx + %d] = atanh(work[env_idx + %d]);",
    OP_ATAN2:               "\n        work[env_idx + %d] = atan2(work[env_idx + %d], work[env_idx + %d]);",
    OP_CONST:               "\n        work[env_idx + %d] = %.16f;",
    OP_INPUT:               "\n        work[env_idx + %d] = inputs[%d][idx * nnz_in[%d] + %d];",
    OP_OUTPUT:              "\n        outputs[%d][idx * nnz_out[%d] + %d] = work[env_idx + %d];",
}

OP_PYTORCH_DICT = {
    OP_ASSIGN:              "\n        work[:, %d] = work[:, %d]",
    OP_ADD:                 "\n        work[:, %d] = work[:, %d] + work[:, %d]",
    OP_SUB:                 "\n        work[:, %d] = work[:, %d] - work[:, %d]",
    OP_MUL:                 "\n        work[:, %d] = work[:, %d] * work[:, %d]",
    OP_DIV:                 "\n        work[:, %d] = work[:, %d] / work[:, %d]",
    OP_NEG:                 "\n        work[:, %d] = -work[:, %d]",
    OP_EXP:                 "\n        work[:, %d] = torch.exp(work[:, %d])",
    OP_LOG:                 "\n        work[:, %d] = torch.log(work[:, %d])",
    OP_POW:                 "\n        work[:, %d] = torch.pow(work[:, %d], work[:, %d])",
    OP_CONSTPOW:            "\n        work[:, %d] = torch.pow(work[:, %d], work[:, %d])",
    OP_SQRT:                "\n        work[:, %d] = torch.sqrt(work[:, %d])",
    OP_SQ:                  "\n        work[:, %d] = work[:, %d] * work[:, %d]",
    OP_TWICE:               "\n        work[:, %d] = 2.*(work[:, %d])",
    OP_SIN:                 "\n        work[:, %d] = torch.sin(work[:, %d])",
    OP_COS:                 "\n        work[:, %d] = torch.cos(work[:, %d])",
    OP_TAN:                 "\n        work[:, %d] = torch.tan(work[:, %d])",
    OP_ASIN:                "\n        work[:, %d] = torch.asin(work[:, %d])",
    OP_ACOS:                "\n        work[:, %d] = torch.acos(work[:, %d])",
    OP_ATAN:                "\n        work[:, %d] = torch.atan(work[:, %d])",
    OP_LT:                  "\n        work[:, %d] = work[:, %d] < work[:, %d]",
    OP_LE:                  "\n        work[:, %d] = work[:, %d] <= work[:, %d]",
    OP_EQ:                  "\n        work[:, %d] = work[:, %d] == work[:, %d]",
    OP_NE:                  "\n        work[:, %d] = work[:, %d] != work[:, %d]",
    OP_NOT:                 "\n        work[:, %d] = torch.logical_not(work[:, %d])",
    OP_AND:                 "\n        work[:, %d] = torch.logical_and(work[:, %d], work[:, %d])",
    OP_OR:                  "\n        work[:, %d] = torch.logical_or(work[:, %d], work[:, %d])",
    OP_FLOOR:               "\n        work[:, %d] = torch.floor(work[:, %d])",
    OP_CEIL:                "\n        work[:, %d] = torch.ceil(work[:, %d])",
    OP_FMOD:                "\n        work[:, %d] = torch.fmod(work[:, %d], work[:, %d])",
    OP_FABS:                "\n        work[:, %d] = torch.abs(work[:, %d])",
    OP_SIGN:                "\n        work[:, %d] = torch.sign(work[:, %d])",
    OP_COPYSIGN:            "\n        work[:, %d] = torch.copysign(work[:, %d], work[:, %d])",
    OP_IF_ELSE_ZERO:        "\n        work[:, %d] = (work[:, %d] == 0) ? 0 : work[:, %d]",
    OP_ERF:                 "\n        work[:, %d] = torch.erf(work[:, %d])",
    OP_FMIN:                "\n        work[:, %d] = torch.fmin(work[:, %d], work[:, %d])",
    OP_FMAX:                "\n        work[:, %d] = torch.fmax(work[:, %d], work[:, %d])",
    OP_INV:                 "\n        work[:, %d] = 1./(work[:, %d])",
    OP_SINH:                "\n        work[:, %d] = torch.sinh(work[:, %d])",
    OP_COSH:                "\n        work[:, %d] = torch.cosh(work[:, %d])",
    OP_TANH:                "\n        work[:, %d] = torch.tanh(work[:, %d])",
    OP_ASINH:               "\n        work[:, %d] = torch.asinh(work[:, %d])",
    OP_ACOSH:               "\n        work[:, %d] = torch.acosh(work[:, %d])",
    OP_ATANH:               "\n        work[:, %d] = torch.atanh(work[:, %d])",
    OP_ATAN2:               "\n        work[:, %d] = torch.atan2(work[:, %d], work[:, %d])",
    OP_CONST:               "\n        work[:, %d] = %f",
    OP_INPUT:               "\n        work[:, %d] = inputs[%d][:, %d]",
    OP_OUTPUT:              "\n        outputs[%d][:, %d] = work[:, %d]",
}

# OP_PYTORCH_DICT_FLAT = {
#     OP_ASSIGN:              "\n        work[%d] = work[%d]",
#     OP_ADD:                 "\n        work[%d] = work[%d] + work[%d]",
#     OP_SUB:                 "\n        work[%d] = work[%d] - work[%d]",
#     OP_MUL:                 "\n        work[%d] = work[%d] * work[%d]",
#     OP_DIV:                 "\n        work[%d] = work[%d] / work[%d]",
#     OP_NEG:                 "\n        work[%d] = -work[%d]",
#     OP_EXP:                 "\n        work[%d] = torch.exp(work[%d])",
#     OP_LOG:                 "\n        work[%d] = torch.log(work[%d])",
#     OP_POW:                 "\n        work[%d] = torch.pow(work[%d], work[%d])",
#     OP_CONSTPOW:            "\n        work[%d] = torch.pow(work[%d], work[%d])",
#     OP_SQRT:                "\n        work[%d] = torch.sqrt(work[%d])",
#     OP_SQ:                  "\n        work[%d] = work[%d] * work[%d]",
#     OP_TWICE:               "\n        work[%d] = 2.*(work[%d])",
#     OP_SIN:                 "\n        work[%d] = torch.sin(work[%d])",
#     OP_COS:                 "\n        work[%d] = torch.cos(work[%d])",
#     OP_TAN:                 "\n        work[%d] = torch.tan(work[%d])",
#     OP_ASIN:                "\n        work[%d] = torch.asin(work[%d])",
#     OP_ACOS:                "\n        work[%d] = torch.acos(work[%d])",
#     OP_ATAN:                "\n        work[%d] = torch.atan(work[%d])",
#     OP_LT:                  "\n        work[%d] = work[%d] < work[%d]",
#     OP_LE:                  "\n        work[%d] = work[%d] <= work[%d]",
#     OP_EQ:                  "\n        work[%d] = work[%d] == work[%d]",
#     OP_NE:                  "\n        work[%d] = work[%d] != work[%d]",
#     OP_NOT:                 "\n        work[%d] = torch.logical_not(work[%d])",
#     OP_AND:                 "\n        work[%d] = torch.logical_and(work[%d], work[%d])",
#     OP_OR:                  "\n        work[%d] = torch.logical_or(work[%d], work[%d])",
#     OP_FLOOR:               "\n        work[%d] = torch.floor(work[%d])",
#     OP_CEIL:                "\n        work[%d] = torch.ceil(work[%d])",
#     OP_FMOD:                "\n        work[%d] = torch.fmod(work[%d], work[%d])",
#     OP_FABS:                "\n        work[%d] = torch.abs(work[%d])",
#     OP_SIGN:                "\n        work[%d] = torch.sign(work[%d])",
#     OP_COPYSIGN:            "\n        work[%d] = torch.copysign(work[%d], work[%d])",
#     OP_IF_ELSE_ZERO:        "\n        work[:, %d] = torch.where(work[:, %d] != 0, work[:, %d], 0)",
#     OP_ERF:                 "\n        work[%d] = torch.erf(work[%d])",
#     OP_FMIN:                "\n        work[%d] = torch.fmin(work[%d], work[%d])",
#     OP_FMAX:                "\n        work[%d] = torch.fmax(work[%d], work[%d])",
#     OP_INV:                 "\n        work[%d] = 1./(work[%d])",
#     OP_SINH:                "\n        work[%d] = torch.sinh(work[%d])",
#     OP_COSH:                "\n        work[%d] = torch.cosh(work[%d])",
#     OP_TANH:                "\n        work[%d] = torch.tanh(work[%d])",
#     OP_ASINH:               "\n        work[%d] = torch.asinh(work[%d])",
#     OP_ACOSH:               "\n        work[%d] = torch.acosh(work[%d])",
#     OP_ATANH:               "\n        work[%d] = torch.atanh(work[%d])",
#     OP_ATAN2:               "\n        work[%d] = torch.atan2(work[%d], work[%d])",
#     OP_CONST:               "\n        work[%d] = %f",
#     OP_INPUT:               "\n        work[%d] = inputs[%d][%d]",
#     OP_OUTPUT:              "\n        outputs[%d][%d] = work[%d]",
# }